### ISSUE TITLE
How to find distance moved in real time using IMU sensor and accelerometer

### ISSUE THREAD

**Issue by akshayacharya97** [mfassler/atdrive-moab#5]
Hello, how can I find the velocity and the direction of the MOAB and the IMU sensor inside it? in the imupacket.py file, there are quaternion variables, gyroscope and magnetometer values. what is lax, lay and laz variables? And where are the accelaration values? I want to calculate the distance moved by the MOAB in real time.

**Comment by mfassler** [comment]
In ImuPacket.py there is 22 bytes of "bnoData".  These 22 bytes come directly from the IMU chip: BNO055.  The data is not altered in any way.  

lax, lay, and laz are "linear acceleration".  gx, gy, gz are "gravity acceleration".  (I assume that "gravity acceleration" is a low-pass filter on the accelerometer, and "linear acceleration" is a high-pass filter on the accelerometer.)

To get movement and direction, you'll have to integrate the "linear acceleration" with respect to time, just like in calculus class (velocity is the time-integral of acceleration).

**Comment by akshayacharya97** [comment]
Thank you. So, do all the variables gx, gy , gz...lax, lay, laz , magx, magy etc come inside bnoData? What is inside bnoData?

Also, the gx gy gz values lie b/w -1000 and 1000 . Even the lax lay and laz values too. Shouldnt it be 0 if the MOAb is stattionary. Garvity is only acting in the z direction and should be 9.8 m/s2 , shouldnt it? What are the units of these variables and how can i use it for the integration? And do you have any references or links i can use for the integration to find distance? I havent performed integration using code before.

**Comment by mfassler** [comment]
If the Moab is not moving, then:

 * lax, lay, lax should be pretty close to zero  (just vibrations)

 * gx, gy, gz  should be pretty close to 980 (the force of gravity)

The unit is:  m/s^2  * 0.01


The internals of the IMU chip are described here:

https://github.com/mfassler/example-device-drivers/tree/master/BNO055-Bosch-9axis-IMU/Notes

... it looks like Github is only previewing the first 50 pages of that PDF.  You'll have to download the pdf.  On page 52 is the contents of bnoData (bytes 0x20 to 0x35)

**Comment by akshayacharya97** [comment]
Ah i see. So for distance, should i integrate gx gy and gz wrt time? Also, did you mean m/s2 * 100? Because the normal value is 9.8m/s2 isnt it? 
The linear accelaration, its between 0 and 10. When does this value change? Upon normal movement about any axis?

**Comment by mfassler** [comment]
Correct.  If you shake the Moab, then the linear acceleration will change.

**Comment by akshayacharya97** [comment]
Which accelaration should be used for integration? And I read that theres an error which accumaltes over time while integrating. A drift of some sort. How to overcome that?

**Comment by mfassler** [comment]
You should use the linear acceleration for motion, lax, lay, laz.  Yes, there is a drift which will accumulate over time.  You'll need some other type of sensor to fix that drift (for example:  a shaft encoder on the wheel can give you absolute speed,  a GPS module can give you absolute position...)  There is no way for the IMU alone to give perfect accuracy (because of drift and rounding errors).

**Comment by akshayacharya97** [comment]
I have a ZED-F9P GPS sensor, how do i configure that and connect it to MOAB for this purpose? Is there a tutorial or website which explains what to do?

**Comment by mfassler** [comment]
From the Moab schematics, you can see that there's a "GPS" port.  By default, the baud rate is 115200, 8N1.  If you attach a GPS here, sending NMEA (ascii) sentences, then the Moab will re-broadcast those NMEA sentences on UDP port 27113.  

To setup the F9P GPS, you should use the "u-center" config program from the U-Blox manufacturer.
